import Link from 'next/link'
import { redirect } from 'next/navigation'
import { getAuthenticatedUser, getOwnData } from '../../lib/supabase-rest'
import LogoutButton from './logout-button'
import BrandLogo from '../brand-logo'

type Profile={full_name:string|null;kyc_status:string}
type Plan={name:string;profit_target_pct:number;daily_loss_limit_pct:number;max_loss_limit_pct:number;min_trading_days:number}
type Account={id:string;display_account_id:string|null;status:string;phase:string;starting_balance:number;balance:number;equity:number;daily_pnl:number;total_pnl:number;trading_days:number;evaluation_step:number;evaluation_steps:number;evaluation_target_pct:number|null;challenge_plans:Plan|null}
type Order={id:string;status:string;amount:number;currency:string;created_at:string;challenge_plans:{name:string;account_size:number}|null}
const usd=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value)

export default async function Dashboard(){
 const auth=await getAuthenticatedUser(); if(!auth) redirect('/auth')
 const profiles=await getOwnData<Profile[]>(`profiles?select=full_name,kyc_status&id=eq.${auth.user.id}&limit=1`,auth.accessToken)
 const accounts=await getOwnData<Account[]>(`trading_accounts?select=id,display_account_id,status,phase,starting_balance,balance,equity,daily_pnl,total_pnl,trading_days,evaluation_step,evaluation_steps,evaluation_target_pct,challenge_plans(name,profit_target_pct,daily_loss_limit_pct,max_loss_limit_pct,min_trading_days)&user_id=eq.${auth.user.id}&order=created_at.desc&limit=1`,auth.accessToken)
 const orders=accounts[0]?[]:await getOwnData<Order[]>(`orders?select=id,status,amount,currency,created_at,challenge_plans(name,account_size)&user_id=eq.${auth.user.id}&order=created_at.desc&limit=1`,auth.accessToken)
 const profile=profiles[0],account=accounts[0],order=orders[0],name=profile?.full_name||auth.user.user_metadata?.full_name||auth.user.email?.split('@')[0]||'Trader'
 if(!account&&order)return <main className="dash"><Aside/><section><header><div><small>TRADER DASHBOARD</small><h1>Welcome, {name}.</h1></div><LogoutButton/></header><div className="emptyState"><span>PAYMENT REVIEW · {order.status.toUpperCase()}</span><h2>Your payment was submitted.</h2><p>We received your {order.amount} {order.currency} payment notification for {order.challenge_plans?.name||'your challenge'}. The transaction is checked on-chain automatically and routed to manual review if needed.</p><Link className="btn" href="/#plans">View challenge rules →</Link><small>ORDER · {order.id.slice(0,8).toUpperCase()} · KYC {(profile?.kyc_status||'not_started').replace('_',' ').toUpperCase()}</small></div></section></main>
 if(!account)return <main className="dash"><Aside/><section><header><div><small>TRADER DASHBOARD</small><h1>Welcome, {name}.</h1></div><LogoutButton/></header><div className="emptyState"><span>YOUR ACCOUNT IS READY</span><h2>Choose your first challenge.</h2><p>Your secure TakeProp profile is active. Select a package to create your first simulated trading account.</p><Link className="btn" href="/#plans">View challenge plans →</Link><small>KYC STATUS · {(profile?.kyc_status||'not_started').replace('_',' ').toUpperCase()}</small></div></section></main>
 const plan=account.challenge_plans,targetPct=account.phase==='funded'?0:Number(account.evaluation_target_pct??plan?.profit_target_pct??0),target=account.starting_balance*targetPct/100,progress=target?Math.max(0,Math.min(100,account.total_pnl/target*100)):100,dailyFloor=account.starting_balance*(1-Number(plan?.daily_loss_limit_pct||0)/100),maxFloor=account.starting_balance*(1-Number(plan?.max_loss_limit_pct||0)/100),daysRequired=Number(plan?.min_trading_days||0)
 return <main className="dash"><Aside/><section><header><div><small>TRADER DASHBOARD</small><h1>Welcome back, {name}.</h1></div><div className="headActions"><button>{account.display_account_id||'TAKEPROP ACCOUNT'}</button><LogoutButton/></div></header><div className="dashCards"><Card l="Balance" v={usd(account.balance)}/><Card l="Equity" v={usd(account.equity)} g/><Card l="Today’s P&L" v={usd(account.daily_pnl)} g={account.daily_pnl>=0}/><Card l="Account status" v={account.status.toUpperCase()} g={account.status==='active'}/></div><div className="stageBanner"><b>{account.phase==='funded'?'FUNDED SIMULATED ACCOUNT':`EVALUATION STEP ${account.evaluation_step} OF ${account.evaluation_steps}`}</b><span>{account.status==='passed'?'Completed — the next account is ready':account.status==='breached'?'Failed — a loss limit was breached':account.phase==='funded'?'Eligible profit is subject to payout and KYC rules':'Meet both the profit target and minimum trading-day rule'}</span></div><div className="dashGrid"><article><header><b>{account.phase==='funded'?'Performance':'Challenge progress'}</b><small>{plan?.name||account.phase.toUpperCase()}</small></header><div className="bigProgress"><b>{usd(account.total_pnl)}</b>{account.phase!=='funded'&&<span> of {usd(target)} target ({targetPct}%)</span>}<i><b style={{width:`${progress}%`}}/></i><strong>{account.phase==='funded'?'Funded performance':`${progress.toFixed(1)}% complete`}</strong></div><div className="riskRows"><div><span>Trading days</span><b>{account.trading_days} / {daysRequired}</b><small>Completed / required</small></div><div><span>Static loss floor</span><b>{usd(maxFloor)}</b><small>{plan?.max_loss_limit_pct||0}% static limit</small></div></div></article><article><header><b>Account</b><small>SIMULATED</small></header><div className="accountInfo"><span>Starting balance<b>{usd(account.starting_balance)}</b></span><span>Phase<b>{account.phase.toUpperCase()}</b></span><span>Daily loss floor<b>{usd(dailyFloor)}</b></span><span>KYC status<b>{(profile?.kyc_status||'not_started').replace('_',' ').toUpperCase()}</b></span></div>{account.status==='active'?<Link className="btn" href="/terminal">Open terminal →</Link>:<Link className="btn" href="/support">Contact support →</Link>}</article></div><div className="disclaimer">All trading activity shown is simulated. Mark price is used for unrealized P&amp;L and risk.</div></section></main>
}
function Aside(){return <aside><BrandLogo priority/><nav><a className="active">Overview</a><Link href="/terminal">Trade</Link><Link href="/terminal">Orders &amp; positions</Link><Link href="/payouts">Payouts</Link><Link href="/kyc">Identity verification</Link><Link href="/notifications">Notifications</Link><Link href="/support">Support</Link></nav><small>SIMULATED ENVIRONMENT</small></aside>}
function Card({l,v,g}:{l:string,v:string,g?:boolean}){return <article><small>{l}</small><b className={g?'green':''}>{v}</b></article>}
