'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import BrandLogo from '../brand-logo'
import './auth.css'
import './legal-checks.css'

export default function AuthPage(){
 const[mode,setMode]=useState<'login'|'register'>('login'),[message,setMessage]=useState(''),[loading,setLoading]=useState(false)
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage('');const form=new FormData(event.currentTarget),response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:form.get('fullName'),email:form.get('email'),password:form.get('password'),acceptedTerms:form.get('acceptedTerms')==='on',acceptedPrivacy:form.get('acceptedPrivacy')==='on',acceptedRisk:form.get('acceptedRisk')==='on',ageConfirmed:form.get('ageConfirmed')==='on'})}),result=await response.json();setLoading(false);if(!response.ok)return setMessage(result.error||'Something went wrong.');if(result.confirmationRequired)return setMessage('Check your email to confirm your account, then sign in.');window.location.href='/dashboard'}
 return <main className="authPage"><section className="authIntro"><BrandLogo priority/><div><span>SIMULATED TRADING · SECURE ACCESS</span><h1>Your trading journey starts here.</h1><p>Create your account, choose a challenge and track every rule from one transparent dashboard.</p></div><small>Protected by encrypted, HTTP-only session cookies.</small></section><section className="authPanel"><div className="authBox"><span>TRADER ACCESS</span><h2>{mode==='login'?'Welcome back.':'Create your account.'}</h2><p>{mode==='login'?'Sign in to your TakeProp dashboard.':'One account for challenges, trading and payouts.'}</p><div className="authTabs"><button type="button" className={mode==='login'?'on':''} onClick={()=>{setMode('login');setMessage('')}}>Log in</button><button type="button" className={mode==='register'?'on':''} onClick={()=>{setMode('register');setMessage('')}}>Register</button></div><form onSubmit={submit}>{mode==='register'&&<label>FULL NAME<input name="fullName" autoComplete="name" minLength={2} required placeholder="Your full name"/></label>}<label>EMAIL<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label><label>PASSWORD<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='register'?12:8} maxLength={128} required placeholder={mode==='register'?'12+ chars with upper, lower, number and symbol':'Your password'}/></label>{mode==='register'&&<div className="legalChecks"><label><input type="checkbox" name="ageConfirmed" required/>I confirm that I am at least 18 and eligible to use the service.</label><label><input type="checkbox" name="acceptedTerms" required/>I accept the <Link href="/terms" target="_blank">Terms of Use</Link>.</label><label><input type="checkbox" name="acceptedPrivacy" required/>I acknowledge the <Link href="/privacy" target="_blank">Privacy Notice</Link>.</label><label><input type="checkbox" name="acceptedRisk" required/>I have read the <Link href="/risk-disclosure" target="_blank">Risk Disclosure</Link>.</label></div>}{message&&<div className="authMessage">{message}</div>}<button className="btn authSubmit" disabled={loading}>{loading?'Please wait…':mode==='login'?'Log in →':'Create account →'}</button></form>{mode==='login'&&<Link className="forgot" href="/forgot-password">Forgot your password?</Link>}</div></section></main>
}
