'use client'
import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import styles from './terminal.module.css'

type Position={id:string;symbol:string;side:'long'|'short';quantity:number;leverage:number;entry_price:number;stop_loss?:number;take_profit?:number;close_reason?:string;exit_price?:number;realized_pnl?:number;fees?:number;opened_at:string;closed_at?:string;metadata:{margin_usdt?:number}}
type PendingOrder={id:string;symbol:string;side:'long'|'short';order_type:'limit'|'stop';margin:number;leverage:number;trigger_price:number;stop_loss?:number;take_profit?:number;created_at:string}
type Snapshot={account:{balance:number;equity:number;starting_balance:number;daily_pnl:number;total_pnl:number;status:string};plan:{name:string;dailyLossPct:number;maxLossPct:number;profitTargetPct:number;maxLeverage:number};positions:Position[];pendingOrders:PendingOrder[];recentTrades:Position[];marks:Record<string,number>;dailyFloor:number;staticFloor:number;unrealizedPnl:number;markSource:string;serverTime:string}
const markets=[['BTCUSDT','BTC / USDT'],['ETHUSDT','ETH / USDT'],['SOLUSDT','SOL / USDT'],['BNBUSDT','BNB / USDT']] as const
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n||0)
const price=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:n<10?4:2}).format(n||0)

export default function TerminalClient({accountId,accountLabel}:{accountId:string;accountLabel:string}){
 const [data,setData]=useState<Snapshot|null>(null),[history,setHistory]=useState<Record<string,number[]>>({}),[symbol,setSymbol]=useState('BTCUSDT'),[side,setSide]=useState<'long'|'short'>('long'),[orderType,setOrderType]=useState<'market'|'limit'|'stop'>('market'),[margin,setMargin]=useState('100'),[leverage,setLeverage]=useState(1),[triggerPrice,setTriggerPrice]=useState(''),[stopLoss,setStopLoss]=useState(''),[takeProfit,setTakeProfit]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const call=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch('/api/trading',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId,...body})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Trading action failed');setData(j);if(j?.marks)setHistory(previous=>Object.fromEntries(Object.entries(j.marks as Record<string,number>).map(([market,mark])=>[market,[...(previous[market]||[]),Number(mark)].slice(-60)])));return j},[accountId])
 const refresh=useCallback(async()=>{try{await call({action:'snapshot'});setError('')}catch(e){setError(e instanceof Error?e.message:'Price refresh failed')}},[call])
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[refresh])
 const positionPnl=useCallback((p:Position)=>{const mark=data?.marks[p.symbol]||p.entry_price;return (p.side==='long'?mark-p.entry_price:p.entry_price-mark)*p.quantity},[data])
 const usedMargin=useMemo(()=>data?.positions.reduce((s,p)=>s+Number(p.metadata?.margin_usdt||0),0)||0,[data])
 async function open(){setBusy(true);setError('');try{await call(orderType==='market'?{action:'open',symbol,side,margin:Number(margin),leverage,stopLoss:Number(stopLoss)||null,takeProfit:Number(takeProfit)||null}:{action:'place_pending',symbol,side,orderType,margin:Number(margin),leverage,triggerPrice:Number(triggerPrice),stopLoss:Number(stopLoss)||null,takeProfit:Number(takeProfit)||null});if(orderType!=='market')setTriggerPrice('')}catch(e){setError(e instanceof Error?e.message:'Order rejected')}finally{setBusy(false)}}
 async function close(p:Position){setBusy(true);setError('');try{await call({action:'close',tradeId:p.id,symbol:p.symbol})}catch(e){setError(e instanceof Error?e.message:'Close rejected')}finally{setBusy(false)}}
 async function cancel(order:PendingOrder){setBusy(true);setError('');try{await call({action:'cancel_pending',orderId:order.id})}catch(e){setError(e instanceof Error?e.message:'Cancellation rejected')}finally{setBusy(false)}}
 const a=data?.account,current=data?.marks[symbol]||0,dailyRoom=a?Math.max(0,a.equity-data!.dailyFloor):0,staticRoom=a?Math.max(0,a.equity-data!.staticFloor):0
 return <main className={styles.shell}>
  <header className={styles.top}><Link href="/dashboard">← Dashboard</Link><div><b>TAKEPROP TERMINAL</b><small>{accountLabel} · SIMULATED</small></div><span className={a?.status==='active'?styles.live:styles.danger}>{a?.status?.toUpperCase()||'CONNECTING'}</span></header>
  <section className={styles.stats}><div><small>BALANCE</small><b>{money(a?.balance||0)}</b></div><div><small>EQUITY</small><b>{money(a?.equity||0)}</b></div><div><small>UNREALIZED P&amp;L</small><b className={(data?.unrealizedPnl||0)>=0?styles.green:styles.red}>{money(data?.unrealizedPnl||0)}</b></div><div><small>USED MARGIN</small><b>{money(usedMargin)}</b></div></section>
  <div className={styles.marketTabs}>{markets.map(([id,label])=><button key={id} className={symbol===id?styles.selected:''} onClick={()=>setSymbol(id)}>{label}<b>{price(data?.marks[id]||0)}</b></button>)}</div>
  <PriceChart points={history[symbol]||[]} label={markets.find(x=>x[0]===symbol)?.[1]||symbol}/>
  <section className={styles.grid}><article className={styles.ticket}><small>ORDER TICKET</small><h1>{markets.find(x=>x[0]===symbol)?.[1]}</h1><div className={styles.quote}><span>MARK PRICE</span><b>{price(current)} USDT</b><i>LIVE · 5 SEC</i></div><div className={styles.orderTypes}>{(['market','limit','stop'] as const).map(type=><button key={type} className={orderType===type?styles.activeType:''} onClick={()=>setOrderType(type)}>{type.toUpperCase()}</button>)}</div><div className={styles.sides}><button className={side==='long'?styles.long:''} onClick={()=>setSide('long')}>LONG</button><button className={side==='short'?styles.short:''} onClick={()=>setSide('short')}>SHORT</button></div>{orderType!=='market'&&<label>Trigger price (USDT)<input inputMode="decimal" value={triggerPrice} onChange={e=>setTriggerPrice(e.target.value)} placeholder={orderType==='limit'?'Desired entry price':'Breakout trigger price'}/></label>}<label>Margin (USDT)<input inputMode="decimal" value={margin} onChange={e=>setMargin(e.target.value)}/></label><label>Leverage<select value={leverage} onChange={e=>setLeverage(Number(e.target.value))}>{[1,2,5,10].filter(x=>x<=(data?.plan.maxLeverage||10)).map(x=><option key={x} value={x}>{x}×</option>)}</select></label><div className={styles.protection}><label>Stop loss (optional)<input inputMode="decimal" value={stopLoss} onChange={e=>setStopLoss(e.target.value)} placeholder="Price"/></label><label>Take profit (optional)<input inputMode="decimal" value={takeProfit} onChange={e=>setTakeProfit(e.target.value)} placeholder="Price"/></label></div><div className={styles.summary}><span>Position notional<b>{money(Number(margin||0)*leverage)}</b></span><span>Est. quantity<b>{current?(Number(margin||0)*leverage/current).toFixed(6):'—'}</b></span></div>{error&&<p className={styles.error}>{error}</p>}<button className={side==='long'?styles.submitLong:styles.submitShort} disabled={busy||!current||a?.status!=='active'||(orderType!=='market'&&!Number(triggerPrice))} onClick={open}>{busy?'Processing…':`${orderType==='market'?'Open':'Place'} ${side==='long'?'long':'short'} ${orderType} →`}</button><small className={styles.source}>{data?.markSource||'Connecting to trusted mark price…'}</small></article>
  <aside className={styles.risk}><small>REAL-TIME RISK ENGINE</small><h2>{data?.plan.name||'Challenge rules'}</h2><Risk label="Daily loss room" value={dailyRoom} base={a?.starting_balance||1} pct={data?.plan.dailyLossPct||0}/><Risk label="Static loss room" value={staticRoom} base={a?.starting_balance||1} pct={data?.plan.maxLossPct||0}/><div className={styles.rule}><span>Daily floor<b>{money(data?.dailyFloor||0)}</b></span><span>Static floor<b>{money(data?.staticFloor||0)}</b></span><span>Profit target<b>{data?.plan.profitTargetPct||0}%</b></span></div><p>Open equity counts toward both limits. A breach locks the account automatically.</p></aside></section>
  <section className={styles.positions}><header><h2>Pending orders</h2><b>{data?.pendingOrders?.length||0}</b></header>{!data?.pendingOrders?.length?<p>No pending orders.</p>:data.pendingOrders.map(o=><article key={o.id}><div><strong>{o.symbol.replace('USDT',' / USDT')}</strong><i className={o.side==='long'?styles.green:styles.red}>{o.side.toUpperCase()} · {o.order_type.toUpperCase()}</i></div><span>Trigger<b>{price(o.trigger_price)}</b></span><span>Margin<b>{money(o.margin)}</b></span><span>Leverage<b>{o.leverage}×</b></span><span>SL / TP<b>{o.stop_loss?price(o.stop_loss):'—'} / {o.take_profit?price(o.take_profit):'—'}</b></span><button disabled={busy} onClick={()=>cancel(o)}>Cancel</button></article>)}</section>
  <section className={styles.positions}><header><h2>Open positions</h2><b>{data?.positions.length||0}</b></header>{!data?.positions.length?<p>No open positions. Choose a market and place your first simulated trade.</p>:data.positions.map(p=><article key={p.id}><div><strong>{p.symbol.replace('USDT',' / USDT')}</strong><i className={p.side==='long'?styles.green:styles.red}>{p.side.toUpperCase()} · {p.leverage}×</i></div><span>Entry<b>{price(p.entry_price)}</b></span><span>Mark<b>{price(data.marks[p.symbol])}</b></span><span>SL / TP<b>{p.stop_loss?price(p.stop_loss):'—'} / {p.take_profit?price(p.take_profit):'—'}</b></span><span>P&amp;L<b className={positionPnl(p)>=0?styles.green:styles.red}>{money(positionPnl(p))}</b></span><button disabled={busy} onClick={()=>close(p)}>Close</button></article>)}</section>
  <section className={styles.positions}><header><h2>Trade history</h2><b>{data?.recentTrades.length||0}</b></header>{!data?.recentTrades.length?<p>Closed trades will appear here.</p>:data.recentTrades.map(p=><article key={p.id}><div><strong>{p.symbol.replace('USDT',' / USDT')}</strong><i className={p.side==='long'?styles.green:styles.red}>{p.side.toUpperCase()} · {p.leverage}×</i></div><span>Entry<b>{price(p.entry_price)}</b></span><span>Exit<b>{price(p.exit_price||0)}</b></span><span>Fees<b>{money(p.fees||0)}</b></span><span>Realized P&amp;L<b className={(p.realized_pnl||0)>=0?styles.green:styles.red}>{money(p.realized_pnl||0)}</b></span></article>)}</section>
  <footer>SIMULATED TRADING ONLY · Market orders use server-validated reference prices from independent market-data providers. Prices may differ from executable exchange prices.</footer>
 </main>
}
function Risk({label,value,base,pct}:{label:string;value:number;base:number;pct:number}){const width=Math.max(0,Math.min(100,value/(base*pct/100||1)*100));return <div className={styles.riskBar}><span>{label}<b>{money(value)}</b></span><i><b style={{width:`${width}%`}}/></i><small>{pct}% limit</small></div>}
function PriceChart({points,label}:{points:number[];label:string}){const values=points.length>1?points:[0,0],min=Math.min(...values),max=Math.max(...values),range=max-min||1,path=values.map((value,index)=>`${index?'L':'M'} ${index/(values.length-1)*100} ${38-(value-min)/range*34}`).join(' '),up=values[values.length-1]>=values[0];return <section className={styles.chart}><header><div><small>LIVE MARK-PRICE CHART</small><h2>{label}</h2></div><div><b className={up?styles.green:styles.red}>{price(values[values.length-1])} USDT</b><small>Last {Math.max(0,points.length*5)} seconds</small></div></header>{points.length<2?<p>Collecting validated price points…</p>:<svg viewBox="0 0 100 40" role="img" aria-label={`${label} recent mark-price chart`} preserveAspectRatio="none"><path className={styles.chartGrid} d="M0 10H100 M0 20H100 M0 30H100"/><path className={up?styles.chartUp:styles.chartDown} d={path}/></svg>}</section>}
