'use client'
import {useMemo,useState} from 'react'
import {money,plans,StepType} from '../lib/plans'
const sizes=[5000,10000,25000,50000,100000]
export default function Home(){const[step,setStep]=useState<StepType>('ONE_STEP');const[size,setSize]=useState(5000);const plan=useMemo(()=>plans.find(p=>p.balance===size&&p.stepType===step)!,[size,step]);return <main>
 <div className="notice">SIMULATED TRADING <i/> UP TO 90% PERFORMANCE REWARDS <i/> STATIC DRAWDOWN</div>
 <header className="nav shell"><a className="brand" href="#top"><b>TP</b><strong>TakeProp</strong></a><nav><a href="#how">How it works</a><a href="#plans">Challenges</a><a href="#rules">Rules</a><a href="#faq">FAQ</a></nav><div><a href="/auth">Log in</a><a className="btn small" href="#plans">Get funded</a></div></header>
 <section className="hero shell" id="top"><div><span className="eyebrow">● BUILT FOR DISCIPLINED CRYPTO TRADERS</span><h1>Your edge.<br/><em>Our capital.</em></h1><p>Prove your strategy in a transparent simulated evaluation. Keep up to 90% of your performance rewards—with no hidden rules, moving drawdown, or time pressure.</p><div className="actions"><a className="btn" href="#plans">Start from $29 →</a><a href="#how">See how it works</a></div><small>✓ No time limit　 ✓ Static 6–8% max loss　 ✓ 80–90% reward split</small></div><Terminal/></section>
 <section className="metrics"><div className="shell"><Metric a="UP TO 90%" b="REWARD SPLIT"/><Metric a="10×" b="MAX LEVERAGE"/><Metric a="0" b="MINIMUM DAYS"/><Metric a="24/7" b="CRYPTO MARKETS"/></div></section>
 <section className="section shell" id="how"><Title over="THE PROCESS" title={<>Three steps to <em>funded.</em></>}/><div className="grid three"><Card n="01" title="Choose your challenge">Select an account size and one-step or two-step evaluation.</Card><Card n="02" title="Prove your edge">Reach the target within fixed, transparent risk limits.</Card><Card n="03" title="Get funded">Complete review and unlock a fresh simulated funded account.</Card></div></section>
 <section className="section dark" id="plans"><div className="shell"><Title over="CHALLENGE PLANS" title={<>Pick your <em>starting line.</em></>}/><div className="toggle"><button className={step==='ONE_STEP'?'on':''} onClick={()=>setStep('ONE_STEP')}>1-Step</button><button className={step==='TWO_STEP'?'on':''} onClick={()=>setStep('TWO_STEP')}>2-Step</button></div><div className="sizes">{sizes.map(x=><button key={x} className={size===x?'on':''} onClick={()=>setSize(x)}>{money(x)}</button>)}</div><div className="plan"><div className="offer"><span>{step==='ONE_STEP'?'ONE-STEP':'TWO-STEP'} CHALLENGE</span><h2>{money(size)}</h2><p>Simulated account balance</p><div className="price"><s>{money(plan.regularPrice)}</s><b>{money(plan.price)}</b><small>one-time</small></div><a className="btn" href={`/checkout?plan=${plan.id}`}>Start challenge →</a><small>No subscription. No hidden fees.</small></div><div className="rules"><Rule a="PROFIT TARGET" b={plan.targets.length===1?'8%': 'Phase 1: 8% · Phase 2: 8%'}/><Rule a="DAILY LOSS LIMIT" b={`3% · ${money(size*.03)}`}/><Rule a="STATIC MAX LOSS" b={`${plan.staticLoss}% · ${money(size*plan.staticLoss/100)}`}/><Rule a="REWARD SPLIT" b={`${plan.rewardSplit}%`} green/><Rule a="TIME LIMIT" b="None"/><Rule a="MINIMUM DAYS" b="0 days"/></div></div><p className="fine">All accounts and trading activity are simulated. Rewards are subject to eligibility, review and agreement.</p></div></section>
 <section className="section shell" id="rules"><Title over="RULES THAT DON'T MOVE" title={<>Built on <em>clarity.</em></>}/><div className="grid four"><Card n="◇" title="3% daily loss">Based on balance at 00:00 UTC. Stale prices never create a breach.</Card><Card n="▱" title="6–8% static max loss">The floor is 94% for 1-Step and 92% for 2-Step and never trails profits.</Card><Card n="◎" title="No time pressure">No deadline and no minimum trading days.</Card><Card n="◈" title="Provable breaches">Every decision stores equity, floor, UTC time and mark-price evidence.</Card></div></section>
 <section className="cta shell"><span>READY TO PROVE YOUR EDGE?</span><h2>Trade with rules you can trust.</h2><p>Choose your challenge and start from $29.</p><a className="btn" href="#plans">View challenge plans →</a></section>
 <section className="section shell faq" id="faq"><Title over="FAQ" title={<>Straight answers.</>}/>{[['Is this real-money trading?','No. All TakeProp accounts and execution are simulated.'],['Does drawdown trail profits?','No. The maximum-loss floor is static at 94% for 1-Step and 92% for 2-Step.'],['How does 2-Step work?','Reach 8% in Phase 1 and 8% in a fresh Phase 2 account.'],['How much do traders keep?','Eligible funded traders receive 80% on 1-Step and 90% on 2-Step.']].map(([q,a])=><details key={q}><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</section>
 <footer><div className="shell foot"><div><a className="brand" href="#top"><b>TP</b><strong>TakeProp</strong></a><p>Trade Crypto. Prove Your Edge. Get Funded.</p></div><div><strong>Product</strong><a href="#plans">Challenges</a><a href="#rules">Rules</a></div><div><strong>Company</strong><a href="#faq">FAQ</a><a href="mailto:support@takeprop.com">Support</a></div><div><strong>Legal</strong><a href="/terms">Terms</a><a href="/privacy">Privacy</a></div></div><div className="shell legal">© 2026 TakeProp. Simulated evaluations only. Nothing on this site is investment advice or brokerage services.</div></footer>
 </main>}
function Title({over,title}:{over:string,title:React.ReactNode}){return <div className="title"><span>{over}</span><h2>{title}</h2></div>}
function Metric({a,b}:{a:string,b:string}){return <div><b>{a}</b><span>{b}</span></div>}
function Card({n,title,children}:{n:string,title:string,children:React.ReactNode}){return <article><b>{n}</b><h3>{title}</h3><p>{children}</p></article>}
function Rule({a,b,green}:{a:string,b:string,green?:boolean}){return <div><small>{a}</small><b className={green?'green':''}>{b}</b></div>}
function Terminal(){return <div className="terminal"><header><span>● TAKEPROP TERMINAL</span><b>SIMULATED</b></header><div className="market"><small>BTC / USDT</small><strong>$64,286.40</strong><em>+2.84%</em><div className="chart">▂▃▂▄▅▄▆▇▆█</div></div><div className="tstats"><Rule a="BALANCE" b="$25,000.00"/><Rule a="EQUITY" b="$25,482.60"/><Rule a="TODAY" b="+$482.60" green/></div><div className="progress"><span>Profit target <b>60%</b></span><i><b/></i><small>$1,517.40 remaining</small></div><div className="trade"><button>LONG</button><button>SHORT</button></div></div>}
