import Link from 'next/link'
import { redirect } from 'next/navigation'
import { getAuthenticatedUser,getOwnData } from '../../lib/supabase-rest'
import PayoutForm from './payout-form'
import styles from './payouts.module.css'
type Account={id:string;display_account_id:string;phase:string;status:string;starting_balance:number;balance:number;challenge_plans:{profit_split_pct:number}|null}
type Request={id:string;amount:number;currency:string;status:string;method:string;requested_at:string;rejection_reason:string|null}
export const dynamic='force-dynamic'
export default async function Payouts(){const auth=await getAuthenticatedUser();if(!auth)redirect('/auth?next=/payouts');const [accounts,requests]=await Promise.all([getOwnData<Account[]>(`trading_accounts?select=id,display_account_id,phase,status,starting_balance,balance,challenge_plans(profit_split_pct)&user_id=eq.${auth.user.id}&phase=eq.funded&status=eq.active&order=created_at.desc&limit=1`,auth.accessToken),getOwnData<Request[]>(`payout_requests?select=id,amount,currency,status,method,requested_at,rejection_reason&user_id=eq.${auth.user.id}&order=requested_at.desc&limit=50`,auth.accessToken)]);const a=accounts[0],reserved=requests.filter(x=>['requested','under_review','approved','processing','paid'].includes(x.status)).reduce((s,x)=>s+Number(x.amount),0),available=a?Math.max(0,(Number(a.balance)-Number(a.starting_balance))*Number(a.challenge_plans?.profit_split_pct||0)/100-reserved):0;return <main className={styles.page}><header><div><small>TAKEPROP PAYOUTS</small><h1>Profit withdrawals</h1><p>Only realized profit from an active funded simulated account is eligible.</p></div><Link href="/dashboard">Dashboard →</Link></header><section className={styles.card}><h2>Available</h2><strong>{available.toFixed(2)} USDT</strong>{a?<><small>{a.display_account_id} · {a.challenge_plans?.profit_split_pct||0}% reward split</small><PayoutForm accountId={a.id} available={available}/></>:<p>A funded account is required before requesting a payout.</p>}</section><section><h2>Request history</h2>{requests.length?<div className={styles.list}>{requests.map(x=><article key={x.id}><b>{Number(x.amount).toFixed(2)} {x.currency}</b><span>{x.method.replace('_',' · ')}</span><strong>{x.status.replace('_',' ').toUpperCase()}</strong><time>{new Date(x.requested_at).toLocaleString('tr-TR')}</time>{x.rejection_reason&&<p>{x.rejection_reason}</p>}</article>)}</div>:<p>No payout requests yet.</p>}</section></main>}
