-- Immutable legal acceptance evidence and network-specific payout validation.
create table if not exists public.legal_acceptances(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,document_version text not null,accepted_terms boolean not null,accepted_privacy boolean not null,accepted_risk boolean not null,age_confirmed boolean not null,evidence_hash text not null,accepted_at timestamptz not null,created_at timestamptz not null default now(),unique(user_id,document_version));
alter table public.legal_acceptances enable row level security;
create policy "Users read own legal acceptances" on public.legal_acceptances for select to authenticated using(user_id=auth.uid());
create policy "Admins read legal acceptances" on public.legal_acceptances for select to authenticated using(exists(select 1 from public.user_roles r where r.user_id=auth.uid() and r.role in('admin','compliance')));
create or replace function public.capture_signup_legal_acceptance() returns trigger language plpgsql security definer set search_path='' as $function$ declare m jsonb:=new.raw_user_meta_data; begin if coalesce((m->>'accepted_terms')::boolean,false) and coalesce((m->>'accepted_privacy')::boolean,false) and coalesce((m->>'accepted_risk')::boolean,false) and coalesce((m->>'age_confirmed')::boolean,false) then insert into public.legal_acceptances(user_id,document_version,accepted_terms,accepted_privacy,accepted_risk,age_confirmed,evidence_hash,accepted_at) values(new.id,coalesce(nullif(m->>'legal_version',''),'unknown'),true,true,true,true,coalesce(nullif(m->>'legal_evidence_hash',''),'unavailable'),coalesce((m->>'legal_accepted_at')::timestamptz,now())) on conflict(user_id,document_version) do nothing; end if; return new; end;$function$;
drop trigger if exists capture_signup_legal_acceptance on auth.users;
create trigger capture_signup_legal_acceptance after insert on auth.users for each row execute function public.capture_signup_legal_acceptance();
create or replace function public.valid_payout_destination(p_method text,p_address text) returns boolean language sql immutable set search_path='' as $function$ select case when p_method in('USDT_BEP20','USDT_ERC20') then p_address ~ '^0x[0-9A-Fa-f]{40}$' when p_method='USDT_TRC20' then p_address ~ '^T[1-9A-HJ-NP-Za-km-z]{33}$' when p_method='USDT_TON' then p_address ~ '^(UQ|EQ)[A-Za-z0-9_-]{46}$' else false end $function$;
create or replace function public.enforce_payout_destination() returns trigger language plpgsql set search_path='' as $function$ begin if not public.valid_payout_destination(new.method,new.destination_ref) then raise exception 'Destination address does not match payout network'; end if; return new; end;$function$;
drop trigger if exists validate_payout_destination on public.payout_requests;
create trigger validate_payout_destination before insert or update of method,destination_ref on public.payout_requests for each row execute function public.enforce_payout_destination();
